services:
  redis:
    image: redis:latest
    container_name: interview_redis
    expose:
      - "6379"
    networks:
      - load-balancing
  
  app1:
    build: .
    container_name: app1
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - load-balancing
  
  app2:
    build: .
    container_name: app2
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - load-balancing

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - load-balancing

networks:
  load-balancing:
